FROM apache/flink:1.18

RUN apt-get update &&     apt-get install -y python3 python3-pip &&  pip3 install apache-flink==1.18.0 py4j==0.10.9.7

# Copy additional JARs without overwriting existing ones
COPY custom-flink-libs/*.jar /opt/flink/lib/

# Copy Python script
COPY lambda_speed_layer.py /opt/flink/usrlib/
COPY kappa_stream_layer.py /opt/flink/usrlib/