scrape_configs:
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:7075']
  
  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker:7075'] 

  -  job_name: 'flink-jobmanager'
     static_configs:
        - targets: ['flink-jobmanager:9250']

  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['flink-taskmanager:9251']

  - job_name: 'flink-kappa-jobmanager'
    static_configs:
      - targets: ['flink-kappa-jobmanager:9252']

  - job_name: 'flink-kappa-taskmanager'
    static_configs:
      - targets: ['flink-kappa-taskmanager:9253']
      
  - job_name: 'kafka'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'kafka-kappa'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['kafka-kappa:7072']

  - job_name: 'postgres-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['postgres-exporter:9187']
